name: Test ubuntu-slim

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  test_ubuntu_slim:
    runs-on: ubuntu-slim
    steps:
      - run: pip install pylint
      - run: pylint --version
      - run: pylint --help