name: CI

on:
  # push:
  #   branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Run a one-line script
        run: echo Hello, world!

      - name: Free space before
        run: |
          echo "Free space before:"
          df -h

      - name: Get number of processors
        run: nproc

  test-mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run a one-line script on macOS
        run: |
          echo Hello from macOS!
          gfortran --version
          gcc --version
          g++ --version
          make --version
